# Generated by Django 3.2.4 on 2021-06-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20210608_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplacedata',
            name='marketplace_id',
        ),
        migrations.AlterField(
            model_name='marketplacedata',
            name='api_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='marketplacedata',
            name='endpoints',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='marketplacedata',
            name='key_security',
            field=models.UUIDField(),
        ),
    ]
